/**
 * Ports owned by the Assessment context.
 */

import type { ItemParameters } from '../domain/irt.js';
import type { AnswerKey, Evaluation, QuestionType } from '../domain/evaluation.js';
import type { Evidence } from '../domain/evidence.js';

export interface QuestionChoiceView {
  readonly id: string;
  readonly text: string;
  readonly orderIndex: number;
  /** Misconception this distractor is designed to expose, when authored. */
  readonly misconceptionKey?: string;
}

export interface QuestionView {
  readonly key: string;
  readonly text: string;
  readonly type: QuestionType;
  readonly choices: readonly QuestionChoiceView[];
  readonly points: number;
  readonly hint?: string | null;
  /** Concept keys this question measures, with link weights. */
  readonly conceptLinks: readonly { conceptKey: string; weight: number; isPrimary: boolean }[];
  readonly irt: ItemParameters;
}

export interface QuestionRepository {
  findByKey(key: string): Promise<QuestionView | null>;
  /** Candidate pool for adaptive selection, scoped to concepts. */
  findPoolByConcepts(conceptKeys: readonly string[], limit?: number): Promise<QuestionView[]>;
  /** Answer keys are loaded separately so they never leak into learner payloads. */
  findAnswerKey(questionKey: string): Promise<AnswerKey | null>;
}

export interface AttemptItemRecord {
  readonly questionKey: string;
  readonly evaluation: Evaluation;
  readonly answeredAt: Date;
  readonly timeSpentSeconds: number | null;
  readonly rawAnswer: Readonly<Record<string, unknown>>;
}

/** Why the learner is answering. Drives evidence weighting and reporting. */
export type AttemptKind = 'PRACTICE' | 'LESSON_CHECK' | 'EXAM' | 'REVIEW' | 'DIAGNOSTIC';

/**
 * A published exam the learner may take, with the concept scope its adaptive
 * engine draws from. The scope comes from the server: the runner passes it to
 * `next-item` unchanged and never decides what an exam measures.
 */
export interface LearnerExamView {
  readonly key: string;
  readonly title: string;
  readonly description: string | null;
  readonly isAdaptive: boolean;
  readonly timeLimitMins: number | null;
  readonly passingScore: number;
  readonly textbookKey: string | null;
  readonly itemCount: number;
  /** Distinct concept keys the exam measures; the whole book when no items. */
  readonly conceptKeys: readonly string[];
}

/** The learner's exam catalogue — published exams for entitled textbooks. */
export interface LearnerExamCatalog {
  examsFor(learnerKey: string): Promise<LearnerExamView[]>;
}

/**
 * A published exam the learner may take, with the concept scope its adaptive
 * engine draws from. The scope comes from the server: the runner passes it to
 * `next-item` unchanged and never decides what an exam measures.
 */
export interface LearnerExamView {
  readonly key: string;
  readonly title: string;
  readonly description: string | null;
  readonly isAdaptive: boolean;
  readonly timeLimitMins: number | null;
  readonly passingScore: number;
  readonly textbookKey: string | null;
  readonly itemCount: number;
  /** Distinct concept keys the exam measures; the whole book when no items. */
  readonly conceptKeys: readonly string[];
}

/** The learner's exam catalogue — published exams for entitled textbooks. */
export interface LearnerExamCatalog {
  examsFor(learnerKey: string): Promise<LearnerExamView[]>;
}

/** `EXPIRED` is distinct from `ABANDONED`: the clock ended it, not the learner. */
export type AttemptStatus = 'IN_PROGRESS' | 'SUBMITTED' | 'ABANDONED' | 'EXPIRED';

export interface AttemptRecord {
  readonly key: string;
  readonly learnerKey: string;
  readonly kind: AttemptKind;
  readonly lessonKey: string | null;
  readonly examKey: string | null;
  readonly status: AttemptStatus;
  readonly startedAt: Date;
  readonly submittedAt: Date | null;
  readonly items: readonly AttemptItemRecord[];
}

export interface ManualReviewQueueItem {
  readonly attemptKey: string;
  readonly attemptStatus: AttemptStatus;
  readonly learnerKey: string;
  readonly learnerName: string | null;
  /** Current learner school id, matching ActorRole.schoolId. */
  readonly schoolId: string | null;
  readonly questionKey: string;
  readonly questionText: string;
  readonly rawAnswer: Readonly<Record<string, unknown>>;
  readonly answeredAt: Date;
  readonly submittedAt: Date | null;
  readonly scorePossible: number;
  readonly note: string | null;
}

export interface ManualReviewListPage {
  readonly rows: readonly ManualReviewQueueItem[];
  readonly total: number;
}

export interface ManualReviewListQuery {
  readonly limit: number;
  readonly offset: number;
  readonly schoolIds?: readonly string[] | undefined;
  readonly learnerKey?: string | undefined;
}

export interface AttemptRepository {
  /** Fresh unique attempt key. Generated by infrastructure, never by a client. */
  nextKey(): string;
  /**
   * The learner's open attempt on this exact scope, if any.
   *
   * Used to resume rather than fork: two concurrent attempts on one lesson
   * would split a learner's evidence across records and make the score
   * ambiguous.
   */
  findOpenByScope(
    learnerKey: string,
    scope: { lessonKey: string | null; examKey: string | null },
  ): Promise<AttemptRecord | null>;
  create(input: {
    key: string;
    learnerKey: string;
    kind: AttemptRecord['kind'];
    lessonKey?: string | null;
    examKey?: string | null;
    startedAt: Date;
  }): Promise<AttemptRecord>;
  findByKey(key: string): Promise<AttemptRecord | null>;
  /** Append one graded answer. Attempts are append-only until submitted. */
  appendItem(attemptKey: string, item: AttemptItemRecord): Promise<void>;
  submit(attemptKey: string, submittedAt: Date, totals: {
    score: number;
    maxScore: number;
    correctCount: number;
    incorrectCount: number;
    pendingReviewCount: number;
  }): Promise<AttemptRecord>;
}

export interface ManualReviewRepository {
  listPendingManualReviews(query: ManualReviewListQuery): Promise<ManualReviewListPage>;
  findPendingManualReview(
    attemptKey: string,
    questionKey: string,
  ): Promise<ManualReviewQueueItem | null>;
  replaceItemEvaluation(input: {
    attemptKey: string;
    questionKey: string;
    evaluation: Evaluation;
    reviewedByUserId: string;
    reviewedAt: Date;
    feedback?: string | null;
  }): Promise<AttemptRecord>;
  updateTotals(attemptKey: string, totals: {
    score: number;
    maxScore: number;
    correctCount: number;
    incorrectCount: number;
    pendingReviewCount: number;
  }): Promise<AttemptRecord>;
}

/**
 * One finished attempt, summarised for a history list (gap G4).
 *
 * Deliberately NOT `AttemptRecord`: that carries every graded item, including
 * the learner's raw answers, and a history list needs none of it. Sending the
 * full record would put an unbounded payload — and the shape of past answers —
 * on a screen that only wants "what did I sit, and how did it go".
 *
 * `score`/`maxScore` are nullable because an attempt can end without being
 * graded (ABANDONED, EXPIRED). Null means "no result", never zero: a learner
 * who walked away did not score 0%.
 */
export interface AttemptSummary {
  readonly key: string;
  readonly kind: AttemptKind;
  readonly status: AttemptStatus;
  readonly lessonKey: string | null;
  readonly examKey: string | null;
  readonly score: number | null;
  readonly maxScore: number | null;
  readonly correctCount: number | null;
  readonly incorrectCount: number | null;
  readonly startedAt: Date;
  readonly submittedAt: Date | null;
}

/**
 * A learner's own assessment history (gap G4).
 *
 * A separate port from `AttemptRepository` on purpose. That one is the
 * write-side aggregate used while an attempt is running; this is a read model
 * for a list screen. Merging them would put a paged, projected query on the
 * interface that `start-attempt` and `submit-answer` depend on.
 */
export interface AttemptHistoryReader {
  /** Most recent first. `limit` is clamped by the caller, never by the client. */
  listForLearner(
    learnerKey: string,
    options: { readonly limit: number; readonly kind?: AttemptKind | undefined },
  ): Promise<readonly AttemptSummary[]>;
}

/**
 * Assessment publishes evidence; Mastery consumes it.
 *
 * The learner is a separate argument rather than a field on Evidence: evidence
 * describes an OBSERVATION (this answer, on this concept, at this time), and
 * who it belongs to is context supplied by the caller. Keeping the learner out
 * of the value object is what lets the same Evidence type be replayed, diffed
 * and unit-tested without inventing a learner.
 */
export interface EvidenceWriter {
  append(learnerKey: string, evidence: readonly Evidence[]): Promise<void>;
}

/** Raised after an attempt is submitted so mastery can recompute. */
export interface MasteryRecomputeTrigger {
  request(learnerKey: string, conceptKeys: readonly string[]): Promise<void>;
}

/**
 * Raised after an answer is graded so engagement can reward it.
 *
 * Assessment reports what happened and never computes a reward: the amount,
 * the streak and the idempotency key are all Engagement's business. Optional on
 * the use case, because grading must not depend on gamification being wired.
 */
export interface RewardTrigger {
  answerGraded(input: {
    learnerKey: string;
    attemptKey: string;
    questionKey: string;
    isCorrect: boolean;
    secondsToAnswer: number | null;
    /** 0..1 difficulty, already normalised from the item's IRT parameter. */
    difficulty: number;
  }): Promise<void>;
}
