import fs from "node:fs/promises";import path from "node:path";import bcrypt from "bcryptjs";import {db} from "../src/db.js";
const p=JSON.parse(await fs.readFile(path.resolve("seeding/question_bank/packages/demo-g07-math.json"),"utf8"));
await db.$transaction(async tx=>{
for(const g of p.grades??[])await tx.grade.upsert({where:{id:g.id},update:g,create:g});
for(const s of p.subjects??[])await tx.subject.upsert({where:{id:s.id},update:s,create:s});
for(const x of p.gradeSubjects??[])await tx.gradeSubject.upsert({where:{gradeId_subjectId:{gradeId:x.gradeId,subjectId:x.subjectId}},update:{isActive:x.isActive},create:x});
for(const b of p.books??[]){const book=await tx.book.upsert({where:{key:b.key},update:{...b,units:undefined},create:{key:b.key,gradeId:b.gradeId,subjectId:b.subjectId,title:b.title,part:b.part,semester:b.semester,edition:b.edition,publisher:b.publisher,publicationYear:b.publicationYear}});for(const u of b.units??[]){const unit=await tx.unit.upsert({where:{key:u.key},update:{bookId:book.id,orderIndex:u.orderIndex,title:u.title},create:{bookId:book.id,key:u.key,orderIndex:u.orderIndex,title:u.title}});for(const l of u.lessons??[]){const lesson=await tx.lesson.upsert({where:{key:l.key},update:{unitId:unit.id,orderIndex:l.orderIndex,title:l.title,branch:l.branch},create:{unitId:unit.id,key:l.key,orderIndex:l.orderIndex,title:l.title,branch:l.branch}});for(const c of l.concepts??[])await tx.concept.upsert({where:{key:c.key},update:{gradeId:c.gradeId,lessonId:lesson.id,orderIndex:c.orderIndex,nameAr:c.nameAr,description:c.description},create:{gradeId:c.gradeId,lessonId:lesson.id,key:c.key,orderIndex:c.orderIndex,nameAr:c.nameAr,description:c.description}});for(const q of l.questions??[]){const question=await tx.question.upsert({where:{key:q.key},update:{lessonId:lesson.id,text:q.text,type:q.type,options:q.options,correctAnswer:q.correctAnswer,explanation:q.explanation,difficulty:q.difficulty,sourcePage:q.sourcePage,origin:q.origin},create:{lessonId:lesson.id,key:q.key,text:q.text,type:q.type,options:q.options,correctAnswer:q.correctAnswer,explanation:q.explanation,difficulty:q.difficulty,sourcePage:q.sourcePage,origin:q.origin}});await tx.questionConcept.deleteMany({where:{questionId:question.id}});for(const key of q.conceptKeys??[]){const c=await tx.concept.findUniqueOrThrow({where:{key}});await tx.questionConcept.create({data:{questionId:question.id,conceptId:c.id}});}}}}}}
for(const x of p.prerequisites??[]){const c=await tx.concept.findUniqueOrThrow({where:{key:x.conceptKey}});const r=await tx.concept.findUniqueOrThrow({where:{key:x.prerequisiteKey}});await tx.conceptPrerequisite.upsert({where:{conceptId_prerequisiteId:{conceptId:c.id,prerequisiteId:r.id}},update:{strength:x.strength??1,requiredMastery:x.requiredMastery??.7},create:{conceptId:c.id,prerequisiteId:r.id,strength:x.strength??1,requiredMastery:x.requiredMastery??.7}});}
const pinHash=await bcrypt.hash("1234",10);const admin=await tx.user.upsert({where:{username:"admin"},update:{},create:{username:"admin",displayName:"مدير النظام",role:"SYSTEM_ADMIN",pinHash}});const parent=await tx.user.upsert({where:{username:"parent"},update:{},create:{username:"parent",displayName:"ولي الأمر",role:"PARENT",pinHash}});const child=await tx.user.upsert({where:{username:"child"},update:{},create:{username:"child",displayName:"الابن",role:"CHILD",pinHash}});void admin;await tx.parentChildLink.upsert({where:{parentId_childId:{parentId:parent.id,childId:child.id}},update:{},create:{parentId:parent.id,childId:child.id}});
});await db.$disconnect();console.log("Seed complete. Demo accounts use PIN 1234.");